# Generated by Django 3.0.5 on 2020-05-13 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200513_0457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='artcile_image',
            new_name='article_image',
        ),
    ]
